# #+title: Substâncias sem nome
# #+subtitle: para orquestra de cordas
# #+author: Davi Raubach
# #+date: 2024
# #+PROPERTY: header-args:lilypond :noweb yes
#+LATEX_HEADER: \usepackage{nopageno}
#+LATEX_HEADER: \usepackage{bicaption}
#+LATEX_CLASS: article
#+LATEX_HEADER: \setcounter{secnumdepth}{0}
# #+LATEX_CLASS_OPTIONS: [article,12pt,openany,oneside,a4paper,english,brazil,sumario=tradicional]
#+OPTIONS: toc:nil
#+LANGUAGE: pt-br


* Apresentação

#+NAME: paragraph
Substâncias sem nome é um dos resultados de uma pesquisa artística que investiga a imaginação criadora em música inspirada em gaston bachelard. a imaginação da liquidez do material musical motiva a composição e pode motivar a performance e escuta da peça. os complexos espectrais utilizados estão sempre a se formar e se deformar, sempre em devir. assim, a peça convida orquestra e ouvintes a imergirem nesta ambiência sonora de temperamento e andamento fluidos.

#+begin_src lilypond :file columns.pdf :results none :export none




    \version "2.25.11"
    \include "org_stylesheet.ily"



    \paper {
    % page-breaking = #ly:one-line-breaking
      page-breaking = #ly:minimal-breaking
  }


  paragraph = "Substâncias sem nome é um dos resultados de uma pesquisa artística que investiga a imaginação criadora em música inspirada em gaston bachelard. a imaginação da liquidez do material musical motiva a composição e pode motivar a performance e escuta da peça. os complexos espectrais utilizados estão sempre a se formar e se deformar, sempre em devir. assim, a peça convida orquestra e ouvintes a imergirem nesta ambiência sonora de temperamento e andamento fluidos."

    \markup {
      \fill-line {
        \override #'(line-width . 45)
        \dir-column {\justify-string {\paragraph}}
        
        \override #'(line-width . 45)
        \dir-column {\justify-string{\paragraph}}
        }
      }


#+end_src

[[file:columns.pdf]]


* Notas de performance

- Todos os naipes apresentam divisi a dois

- Não há necessidade de afinar os quartos de tom precisamente.

- Trêmolos: sempre o mais rápido possível

- Indicações de posição de arco
  
  st.: sul tasto

  sp.: sul ponticello

  esp.: extremamente sul ponticello

  ord.: posição ordinária


